version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      TYPEORM_ENTITIES: dist/configuration/typeorm/entities/*.js
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_lucas_soler
    ports:
      - "5432:5432"